;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282828
background-alt = #3c3836
foreground = #ebdbb2
primary = #d79921
secondary = #83a598
alert = #cc241d
disabled = #a89984

[gruvbox]
black= #000000
dark= #1d1d1d
disabled= #262626
red= #ea6962
red-alt= #b22222
orange= #fe8019
orange-mat=#e78a4e
yellow= #fabd2f
yellow-mat=#d8a657
green= #b8bb26
green-alt=#98971a
aqua= #8ec07c
aqua-alt= #689d6a
blue= #458588
blue-alt=#83a598
grey= #313131
dark-grey=#222222
cream= #fff4d2
white= #FFFFFF
transparent= #00000000
Stransparent= #CC000000

[bar/example]
width = 100%
height = 20pt
radius = 6
bottom = false
; dpi = 96

background = ${gruvbox.transparent}
foreground = ${gruvbox.cream}
border-size = 3pt
border-color = ${gruvbox.transparent}
module-margin = 0
padding-left= 4pt
padding-right= 4pt
separator ="  "
separator-foreground = ${gruvbox.transparent}

line-size = 3pt

font-0 = NotoSans Nerd Font:size=10:weight=bold;1

modules-left = power-menu xwindow windows i3 rmpc
; rmpc (tem q achar um lugar pra por)
modules-center = rofi time pulseaudio
modules-right = tray filesystem memory cpu temp

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

 wm-restack = i3
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/rofi]
type=custom/text
content=" 󰣇 "
content-padding=2
click-left= exec rofi -show drun -disable-history -show-icons
content-foreground= ${gruvbox.blue-alt}
content-background= ${gruvbox.black}

[module/tray]
type=internal/tray
format = <tray>
format-prefix = " 󱊖   "
format-prefix-foreground = ${gruvbox.orange}
format-prefix-background = ${gruvbox.black}

tray-spacing= 8px
format-padding=5px
format-background=${gruvbox.black}
tray-background = ${gruvbox.black}

[module/xwindow]
type = internal/xwindow
format-prefix="      "
format-prefix-foreground=${gruvbox.yellow-mat}
format-prefix-background=${gruvbox.black}

label = %class%
label-maxlen=40
label-foreground = ${gruvbox.cream}
label-background= ${gruvbox.dark}
label-padding-left=2
label-padding-right=2

[module/filesystem]
type = internal/fs
interval = 30
mount-0 = /
format-mounted-prefix = "      "

format-mounted-prefix-foreground = ${gruvbox.red}
format-mounted-prefix-background= ${gruvbox.black}

label-mounted = %percentage_used%%

label-mounted-foreground = ${gruvbox.cream}
label-mounted-background= ${gruvbox.dark}

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

label-mounted-padding-left=2
label-mounted-padding-right=2

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "     "
format-volume-prefix-foreground = ${gruvbox.cream}
format-volume-prefix-background= ${gruvbox.black}
format-volume = <label-volume>

label-volume = %percentage%%
label-volume-foreground= ${gruvbox.cream}
label-volume-background= ${gruvbox.dark}
label-volume-padding-left=2
label-volume-padding-right=2

format-muted-prefix = "    "
format-muted-foreground = ${gruvbox.orange}
format-muted-background = ${gruvbox.black}

label-muted = muted
label-muted-foreground = ${gruvbox.orange-mat}
label-muted-background = ${gruvbox.dark}
label-muted-padding-left=2
label-muted-padding-right=2

[module/memory]
type = internal/memory
interval = 2
format-prefix = "      "
format-prefix-foreground = ${gruvbox.yellow}
format-prefix-background= ${gruvbox.black}

label = %mb_used%
label-foreground = ${gruvbox.cream}
label-background= ${gruvbox.dark}
label-padding-left=2
label-padding-right=2

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "      "
format-prefix-foreground = ${gruvbox.orange-mat}
format-prefix-background= ${gruvbox.black}

label = %percentage%%
label-foreground = ${gruvbox.cream}
label-background= ${gruvbox.dark}
label-padding-left=2
label-padding-right=2

[module/time]
type = internal/date
interval = 30
format-prefix = "    "
format-prefix-foreground=${gruvbox.aqua}
format-prefix-background=${gruvbox.black}

date = %A  %d %b %Y | %H:%M 
label =%date% 
label-foreground = ${gruvbox.cream}
label-background= ${gruvbox.dark}
label-padding-left=2
label-padding-right=2
label-click-left = yad --calendar

[module/temp]
type = internal/temperature
interval = 5
thermal-zone = 0
hwmon-path = /sys/class/hwmon/hwmon1/temp1_input
base-temperature = 20 
warn-temperature = 70
units = true

format =<label>
format-prefix = "    "
format-prefix-foreground= ${gruvbox.green} 
format-prefix-background= ${gruvbox.black}

label = %temperature-c%
label-foreground = ${gruvbox.cream}
label-background= ${gruvbox.dark}
label-padding-left=2
label-padding-right=2

format-warn-prefix = "    "
format-warn-prefix-foreground= ${gruvbox.red}
format-warn-prefix-background= ${gruvbox.black}

label-warn = %temperature-c%
label-warn-foreground = ${gruvbox.cream}
label-warn-background= ${gruvbox.dark}
label-warn-padding-left=2
label-warn-padding-right=2

[module/network]
type = internal/network
interface = enp4s0
interval = 3
accumulate-stats = true
unknown-as-up = true
speed-unit = "b"

; Formatos corretos
format-connected = "   󰛳   "
format-connected-foreground = ${gruvbox.green}
format-connected-background = ${gruvbox.black}
format-connected-padding-left=2
format-connected-padding-right=2

format-disconnected = "      "
format-disconnected-foreground = ${gruvbox.red}
format-disconnected-background = ${gruvbox.dark}
format-disconnected-padding-left=2
format-disconnected-padding-right=2

[module/windows]
type = custom/script
exec = ~/.config/polybar/window-list.sh
interval = 1
format = <label>
label = %output%
format-padding = 1
maxlen = 50

format-background = ${gruvbox.black}


[module/rmpc]
type = custom/script
exec = ~/.config/polybar/rmpc-module.sh
interval = 1
tail = true
format = <label>
label = %output%
format-padding = 1
format-foreground = ${gruvbox.cream}
format-background = ${gruvbox.black}

; Ações de controle
;click-left = rmpc togglepause
;click-right = rmpc next
;click-middle = rmpc prev
scroll-up = rmpc volume +5
scroll-down = rmpc volume -5

[module/power-menu]
type = custom/text
content = "  ⏻  "
click-left = ~/.config/polybar/power-menu.sh
content-foreground = ${gruvbox.cream}
content-background = ${gruvbox.black}
content-padding = 1

[module/i3]
type = internal/i3
enable-scroll = false
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
fuzzy-match = true

ws-icon-0 = 1;󰈹
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;󰭛
ws-icon-6 = 7;󱓷
ws-icon-7 = 8;󰚀

format = <label-state> <label-mode>
label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${gruvbox.red-alt} 
label-mode-foreground = ${gruvbox.white}

label-focused = %icon%
label-focused-font = 5
label-focused-foreground = ${gruvbox.yellow}
label-focused-background= ${gruvbox.black}
label-focused-padding = 2

label-unfocused = %icon%
label-unfocused-font = 5
label-unfocused-foreground = ${gruvbox.cream}
label-unfocused-background= ${gruvbox.black}
label-unfocused-padding = 2

label-visible = %icon%
label-visible-padding = 2

label-urgent = %icon%
label-urgent-font = 5
label-urgent-foreground = ${gruvbox.red-alt}
label-urgent-background= ${gruvbox.black}
label-urgent-padding = 2

label-separator = ""
label-separator-padding = 0
label-separator-foreground = ${gruvbox.transparent}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini


